### ISSUE TITLE
Consider adding a requirements.txt file to install dependencies

### ISSUE THREAD

**Issue by nstarke** [efchatz/WPAxFuzz#1]
looks like the following pypi packages are required for normal usage:
```
pandas
```

otherwise consider adding instructions on installing pandas to the readme? happy to submit a pr if necessary, just let me know what route you want to go down.  thanks

**Comment by efchatz** [comment]
Thank you very much for informing us about the pandas issue and the suggestion. Indeed, the pandas is missing from the readme file. We will include it in the following days. We probably also add a requirements file to the repo, for an easier setup process.

**Comment by byrkam** [comment]
As it seems there was a forgotten, unused import of the pandas package in Mngmt_frames/Construct_frame_fields.py file. A requirements.txt file has been also added
